# File: Makefile
# -----------------------------------------------------------------------------
# DOCUMENT = Dissertationtitle.pdf - Name of the document, change the 'Dissertationtitle' to whatever you like, but do include the .pdf
# COMPILER = latexmk               - The "compiler" used for generating the DOCUMENT from a given LaTeX file(s)
# BUILD    = tmp                   - Name of the build directory that contains the compiled .pdf file, but also some intermediate files generated by 'latexmk'
# FLAGS    = -pdf -outdir=$(BUILD) - Compilation options for 'latexmk':
# 								     -pdf    : generates the DOCUMENT .pdf-file using 'pdflatex'
# 								     -outdir : generates all files (incl. intermediate compilation files) to BUILD
# MAINF    = main.tex              - main target LaTeX file for containing all the necessary files needed for the document
# -----------------------------------------------------------------------------

DOCUMENT = Dissertationtitle.pdf
COMPILER = latexmk
FLAGS    = -pdf -outdir=$(BUILD)
MAINF    = main.tex
BUILD    = tmp

all:
	@ $(COMPILER) $(FLAGS) $(MAINF)
	@ mv -v $(BUILD)/main.pdf ./$(DOCUMENT)

clean:
	@ rm -r $(BUILD)

help:
	@ echo "Make args:"
	@ echo "make       ....... build document"
	@ echo "make clean ....... remove build files"
	@ echo "make help  ....... print this help"
